library(readxl)
moa=read_excel("C:/Users/Lisheng/Desktop/MOAData.xlsx")
View(moa)

a)
colnames(moa)=c("race","year","metro","HD","Expectancy","graddegree","schoolenroll","earning","health","education","income")
boxplot(HD~race,data=moa,main="HD Index boxplot by race group",xlab="race",ylab="HD Index",names=c("African American","Asian American","Latino","White"))

b)
additive_lm=lm(HD~earning+factor(race),data=moa)
summary(additive_lm)

c)
interaction_lm=lm(HD~earning+factor(race)+earning*factor(race),data=moa)
summary(interaction_lm)

d)
install.packages("ggplot2")
library(ggplot2)
install.packages("visreg")
library(visreg)
visreg(additive_lm,"earning",by="race",whitespace=0.5,overlay=TRUE,band=FALSE,points.par=list(cex=1.1))
ggplot(data=moa,aes(x=earning,y=HD,colour=factor(race)))+stat_smooth(method=lm,fullrange=FALSE)+geom_point()

e)
install.packages("car")
library(car)
threepredictor_lm=lm(HD~Expectancy+earning+factor(race),data=moa)
summary(threepredictor_lm)
par(mfrow=c(2,2))
residualPlots(threepredictor_lm)
shapiro.test(threepredictor_lm$residuals)
ncvTest(threepredictor_lm)

f)
par(mfrow=c(1,1))
qqPlot(threepredictor_lm,id.n=2)
outlierTest(threepredictor_lm)
influenceIndexPlot(threepredictor_lm,id.n=2)
influencePlot(threepredictor_lm,id.n=2)

g)
null=lm(HD~1,data=moa)
summary(null)
full=lm(HD~Expectancy+earning+factor(race),data=moa)
summary(full)
step(null,scope=list(lower=null,upper=full),direction="forward")
